-- Manufacturing Intelligence Demo - Core Tables
-- Simple, clean table definitions

USE DATABASE MANUFACTURING_DEMO;
USE SCHEMA DEMO_DATA;
USE WAREHOUSE DEMO_WH;

-- Plants table
CREATE OR REPLACE TABLE PLANTS (
    PLANT_ID STRING,
    PLANT_NAME STRING,
    REGION STRING,
    COUNTRY STRING
);

-- Inventory table
CREATE OR REPLACE TABLE INVENTORY (
    ITEM_ID STRING,
    ITEM_NAME STRING,
    PLANT_ID STRING,
    CATEGORY STRING,
    CURRENT_STOCK NUMBER,
    REORDER_POINT NUMBER,
    UNIT_COST NUMBER
);

-- Suppliers table
CREATE OR REPLACE TABLE SUPPLIERS (
    SUPPLIER_ID STRING,
    SUPPLIER_NAME STRING,
    COUNTRY STRING,
    PERFORMANCE_SCORE NUMBER,
    RISK_SCORE NUMBER
);

-- Production table
CREATE OR REPLACE TABLE PRODUCTION (
    PRODUCTION_ID STRING,
    PLANT_ID STRING,
    PRODUCT_NAME STRING,
    PRODUCTION_DATE DATE,
    QUANTITY NUMBER,
    EFFICIENCY_PERCENT NUMBER
);

-- Financial KPIs table
CREATE OR REPLACE TABLE FINANCIAL_KPIS (
    KPI_DATE DATE,
    PLANT_ID STRING,
    INVENTORY_VALUE NUMBER,
    WORKING_CAPITAL NUMBER,
    COST_SAVINGS NUMBER
);

-- Test tables created
SELECT 'Tables created successfully' AS STATUS;
